/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gui;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage stage) throws IOException {
//        String javaVersion = System.getProperty("java.version");
//        String javafxVersion = System.getProperty("javafx.version");
//        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
//        Label l2 = new Label("Hello, world");
//        VBox root = new VBox(l, l2);
////        Scene scene = new Scene(new StackPane(root), 640, 480);
//        Scene scene = new Scene (root, 640, 480);
////        ((StackPane)scene.getRoot()).getChildren().add(l2);
//        stage.setScene(scene);
//        stage.show();
    	
    	  Parent root = FXMLLoader.load(getClass().getResource("viewsandcontrollers/main/Main.fxml"));
          Scene scene = new Scene(root);
          stage.setScene(scene);
          stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
